library(rvest)
library(dplyr)
library(robotstxt)
Path=paths_allowed("https://www.imdb.com/list/ls099950496/")
link<-"https://www.imdb.com/list/ls099950496/"
web<-read_html(link)
name=web%>%html_nodes(".lister-item-header a")%>%html_text()
View(name)
year=web%>%html_nodes(".text-muted.unbold")%>%html_text()
View(year)
rating<-web%>%html_nodes(".ipl-rating-star__rating")%>%html_text()
View(rating)
duration<-web%>%html_nodes(".runtime")%>%html_text()
View(duration)
genre<-web%>%html_nodes(".genre")%>%html_text()
View(genre)
imdbratingstel<-data.frame(name,year,rating,duration,genre)
View(imdbratingstel)
write.csv(imdbratingstel,"My_movie data.csv")

